### PR TITLE
Updated to be compatible with leaflet-1.0.0 & ember-leaflet-3.0.2+

### PR DESCRIPTION
**Pull request by fpauser**

### CODE REVIEW

**Comment by miguelcobain** [comment]
Looks like this addon suffered a massive simplification.

**Comment by fpauser** [comment]
Hopefully I didn't oversimplify that thing ;) - it works fine  in our app.

**Comment by fpauser** [comment]
Just saw that I left `isDevelopingPlugin` in - update is coming.

**Comment by miguelcobain** [comment]
LGTM.
README needs update.
Also, the major version should be bumped upon merge.

**Comment by fpauser** [comment]
@miguelcobain What is missing in README?

**Comment by miguelcobain** [comment]
@fpauser the README example should use popup-layer introduced in ember-leaflet 3.

**Pull request merged**
